<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);1701;1702;1705</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Watch Include="**/*.cs"
          Exclude="
            bin/**;
            obj/**;
            TestResults/**;
            coverage-html/**;
            docs/**;
            backups/**;
            Migrations/**;
            wwwroot/**
          " />
  </ItemGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'ALOud.Tests'">
    <MSBuildProjectExtensionsPath>obj/ALOud.Tests/</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>obj/ALOud.Tests/</BaseIntermediateOutputPath>
    <IntermediateOutputPath>obj/ALOud.Tests/$(Configuration)/</IntermediateOutputPath>
    <BaseOutputPath>bin/ALOud.Tests/</BaseOutputPath>
  </PropertyGroup>
</Project>