services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=g849eYMeH6mmJGE2*8ku
            - MSSQL_PID=Developer
        ports:
            - "1444:1433"
        volumes:
            - mssql_data:/var/opt/mssql
        restart: unless-stopped

    qdrant:
        image: qdrant/qdrant:v1.9.1
        container_name: qdrant
        ports:
            - "6333:6333" # REST API
            - "6334:6334" # gRPC (optional)
        volumes:
            - qdrant_data:/qdrant/storage
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    qdrant_data:
    mssql_data:
